<?php

namespace ContainerSD8AU0g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_65Or4a1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.65Or4a1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.65Or4a1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repository_departement' => ['privates', 'App\\Repository\\DepartementRepository', 'getDepartementRepositoryService', true],
            'repository_ville' => ['privates', 'App\\Repository\\VilleRepository', 'getVilleRepositoryService', true],
        ], [
            'repository_departement' => 'App\\Repository\\DepartementRepository',
            'repository_ville' => 'App\\Repository\\VilleRepository',
        ]);
    }
}
