<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOTZWgCy\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOTZWgCy/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerOTZWgCy.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerOTZWgCy\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerOTZWgCy\App_KernelProdContainer([
    'container.build_hash' => 'OTZWgCy',
    'container.build_id' => '7f9f5694',
    'container.build_time' => 1607013040,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOTZWgCy');
