<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_home_departement' => [['id'], ['_controller' => 'App\\Controller\\HomeController::departement'], ['id' => '\\d+'], [['variable', '-', '\\d+', 'id', true], ['text', '/departement']], [], []],
    'app_home_ville' => [['id', 'ville'], ['_controller' => 'App\\Controller\\HomeController::ville'], [], [['variable', '/', '[^/]++', 'ville', true], ['variable', '-', '[^/]++', 'id', true], ['text', '/departement']], [], []],
    'app_home_lieu' => [['id', 'ville', 'lieu'], ['_controller' => 'App\\Controller\\HomeController::lieu'], [], [['variable', '/', '[^/]++', 'lieu', true], ['variable', '/', '[^/]++', 'ville', true], ['variable', '-', '[^/]++', 'id', true], ['text', '/departement']], [], []],
    'app_home_selection' => [[], ['_controller' => 'App\\Controller\\HomeController::selection'], [], [['text', '/notre-selection']], [], []],
    'app_home_visite' => [[], ['_controller' => 'App\\Controller\\HomeController::visite'], [], [['text', '/les-plus-visites']], [], []],
    'app_home_nous' => [[], ['_controller' => 'App\\Controller\\HomeController::nous'], [], [['text', '/notre-equipe']], [], []],
    'app_home_contact' => [[], ['_controller' => 'App\\Controller\\HomeController::contact'], [], [['text', '/contact']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
];
