<?php

namespace ContainerOTZWgCy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6qyvf6CService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.6qyvf6C' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6qyvf6C'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repository_lieu' => ['privates', 'App\\Repository\\LieuRepository', 'getLieuRepositoryService', true],
        ], [
            'repository_lieu' => 'App\\Repository\\LieuRepository',
        ]);
    }
}
