<?php

namespace ContainerOTZWgCy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'http-kernel'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ArgumentValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'http-kernel'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ArgumentResolver'.\DIRECTORY_SEPARATOR.'ServiceValueResolver.php';

        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\HomeController::contact' => ['privates', '.service_locator.Om4dtJv', 'get_ServiceLocator_Om4dtJvService', true],
            'App\\Controller\\HomeController::departement' => ['privates', '.service_locator.65Or4a1', 'get_ServiceLocator_65Or4a1Service', true],
            'App\\Controller\\HomeController::lieu' => ['privates', '.service_locator.6qyvf6C', 'get_ServiceLocator_6qyvf6CService', true],
            'App\\Controller\\HomeController::selection' => ['privates', '.service_locator.6qyvf6C', 'get_ServiceLocator_6qyvf6CService', true],
            'App\\Controller\\HomeController::ville' => ['privates', '.service_locator.D6judUQ', 'get_ServiceLocator_D6judUQService', true],
            'App\\Controller\\HomeController::visite' => ['privates', '.service_locator.6qyvf6C', 'get_ServiceLocator_6qyvf6CService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\HomeController:contact' => ['privates', '.service_locator.Om4dtJv', 'get_ServiceLocator_Om4dtJvService', true],
            'App\\Controller\\HomeController:departement' => ['privates', '.service_locator.65Or4a1', 'get_ServiceLocator_65Or4a1Service', true],
            'App\\Controller\\HomeController:lieu' => ['privates', '.service_locator.6qyvf6C', 'get_ServiceLocator_6qyvf6CService', true],
            'App\\Controller\\HomeController:selection' => ['privates', '.service_locator.6qyvf6C', 'get_ServiceLocator_6qyvf6CService', true],
            'App\\Controller\\HomeController:ville' => ['privates', '.service_locator.D6judUQ', 'get_ServiceLocator_D6judUQService', true],
            'App\\Controller\\HomeController:visite' => ['privates', '.service_locator.6qyvf6C', 'get_ServiceLocator_6qyvf6CService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\HomeController::contact' => '?',
            'App\\Controller\\HomeController::departement' => '?',
            'App\\Controller\\HomeController::lieu' => '?',
            'App\\Controller\\HomeController::selection' => '?',
            'App\\Controller\\HomeController::ville' => '?',
            'App\\Controller\\HomeController::visite' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\HomeController:contact' => '?',
            'App\\Controller\\HomeController:departement' => '?',
            'App\\Controller\\HomeController:lieu' => '?',
            'App\\Controller\\HomeController:selection' => '?',
            'App\\Controller\\HomeController:ville' => '?',
            'App\\Controller\\HomeController:visite' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]));
    }
}
