<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container63CmRSN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container63CmRSN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container63CmRSN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container63CmRSN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container63CmRSN\App_KernelDevDebugContainer([
    'container.build_hash' => '63CmRSN',
    'container.build_id' => '1e37a5b4',
    'container.build_time' => 1607540807,
], __DIR__.\DIRECTORY_SEPARATOR.'Container63CmRSN');
