<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSD8AU0g\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSD8AU0g/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSD8AU0g.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSD8AU0g\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSD8AU0g\App_KernelDevDebugContainer([
    'container.build_hash' => 'SD8AU0g',
    'container.build_id' => '1d17bb27',
    'container.build_time' => 1607103913,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSD8AU0g');
