<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'app_home_departement' => [['id'], ['_controller' => 'App\\Controller\\HomeController::departement'], ['id' => '\\d+'], [['variable', '-', '\\d+', 'id', true], ['text', '/departement']], [], []],
    'app_home_ville' => [['id', 'ville'], ['_controller' => 'App\\Controller\\HomeController::ville'], [], [['variable', '/', '[^/]++', 'ville', true], ['variable', '-', '[^/]++', 'id', true], ['text', '/departement']], [], []],
    'app_home_lieu' => [['id', 'ville', 'lieu'], ['_controller' => 'App\\Controller\\HomeController::lieu'], [], [['variable', '/', '[^/]++', 'lieu', true], ['variable', '/', '[^/]++', 'ville', true], ['variable', '-', '[^/]++', 'id', true], ['text', '/departement']], [], []],
    'app_home_selection' => [[], ['_controller' => 'App\\Controller\\HomeController::selection'], [], [['text', '/notre-selection']], [], []],
    'app_home_visite' => [[], ['_controller' => 'App\\Controller\\HomeController::visite'], [], [['text', '/les-plus-visites']], [], []],
    'app_home_nous' => [[], ['_controller' => 'App\\Controller\\HomeController::nous'], [], [['text', '/notre-equipe']], [], []],
    'app_home_contact' => [[], ['_controller' => 'App\\Controller\\HomeController::contact'], [], [['text', '/contact']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
];
