<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Lieu extends \App\Entity\Lieu implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'photo', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'prix', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'horaires', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'transport', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'evenement', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'site_internet', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'lien_maps', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'code_postal', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'VilleReferente', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'notre_selection', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'plus_visite'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'photo', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'prix', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'horaires', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'transport', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'evenement', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'site_internet', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'lien_maps', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'code_postal', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'VilleReferente', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'notre_selection', '' . "\0" . 'App\\Entity\\Lieu' . "\0" . 'plus_visite'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Lieu $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): \App\Entity\Lieu
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Lieu
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', []);

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto(string $photo): \App\Entity\Lieu
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', [$photo]);

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(string $type): \App\Entity\Lieu
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix(?string $prix): \App\Entity\Lieu
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraires(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraires', []);

        return parent::getHoraires();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraires(?string $horaires): \App\Entity\Lieu
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraires', [$horaires]);

        return parent::setHoraires($horaires);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse(string $adresse): \App\Entity\Lieu
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransport(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransport', []);

        return parent::getTransport();
    }

    /**
     * {@inheritDoc}
     */
    public function setTransport(?string $transport): \App\Entity\Lieu
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransport', [$transport]);

        return parent::setTransport($transport);
    }

    /**
     * {@inheritDoc}
     */
    public function getEvenement(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEvenement', []);

        return parent::getEvenement();
    }

    /**
     * {@inheritDoc}
     */
    public function setEvenement(string $evenement): \App\Entity\Lieu
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEvenement', [$evenement]);

        return parent::setEvenement($evenement);
    }

    /**
     * {@inheritDoc}
     */
    public function getSiteInternet(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiteInternet', []);

        return parent::getSiteInternet();
    }

    /**
     * {@inheritDoc}
     */
    public function setSiteInternet(?string $site_internet): \App\Entity\Lieu
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSiteInternet', [$site_internet]);

        return parent::setSiteInternet($site_internet);
    }

    /**
     * {@inheritDoc}
     */
    public function getLienMaps(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLienMaps', []);

        return parent::getLienMaps();
    }

    /**
     * {@inheritDoc}
     */
    public function setLienMaps(string $lien_maps): \App\Entity\Lieu
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLienMaps', [$lien_maps]);

        return parent::setLienMaps($lien_maps);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePostal(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePostal', []);

        return parent::getCodePostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePostal(int $code_postal): \App\Entity\Lieu
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePostal', [$code_postal]);

        return parent::setCodePostal($code_postal);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleReferente(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleReferente', []);

        return parent::getVilleReferente();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleReferente(string $VilleReferente): \App\Entity\Lieu
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleReferente', [$VilleReferente]);

        return parent::setVilleReferente($VilleReferente);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotreSelection(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotreSelection', []);

        return parent::getNotreSelection();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotreSelection(bool $notre_selection): \App\Entity\Lieu
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotreSelection', [$notre_selection]);

        return parent::setNotreSelection($notre_selection);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlusVisite(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlusVisite', []);

        return parent::getPlusVisite();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlusVisite(bool $plus_visite): \App\Entity\Lieu
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlusVisite', [$plus_visite]);

        return parent::setPlusVisite($plus_visite);
    }

}
